\pdfoutput=1

\documentclass[a4paper]{l4proj}
\usepackage{fullpage}
\usepackage{indentfirst}

\begin{document}
\title{Code Fuzzing for Investigating Stress Points in Sociotechnical Systems}  % To be changed!
\author{Tom Wallis}
\date{\today}
\maketitle

\begin{abstract}

\end{abstract}

\educationalconsent
\tableofcontents

\chapter{Introduction}
\label{intro}

\section{Preliminaries}
\label{preliminaries}
Sociotechnical systems are...
Models are...
Code fuzzing is...
Emergant behaviour in a sociotechnical system is...

\section{Terminology}
\label{introducing_technology}
In the context of this project, when \emph{atoms} refer to...
In addition, the general model laid out in this project is composed of flow, atoms, ... which mean... the model therefore has the following hierarchical structure...

\chapter{Motivations}
\label{motivations}
Difficulty of creating sociotechnical systems to test
Because of emergant behaviour in the sociotechnical system, testing is difficult...
Learning from testing with software engineering...


\section{Aims}
\label{aims}
Actual focus of the project...
Intended outcome/areas of results of interest...


\section{Outline}
\label{outline}


\chapter{Research}
\label{research_head}


\section{Planning and things learned from research}  % This needs a better name, for certain! Is it even needed?
\label{planning_head}

\chapter{Implementation}
\label{implementation_head}

\section{Model Outline}
\label{model_outline}


\chapter{Experimental Results}
\label{experimental_results}


\chapter{Evaluation}
\label{evaluation}

\chapter{Future Work}
\label{semantics}
\section{A mathematical sociotechnical model}
One piece of work which could be undertaken in the future would be to use the principles from this model to create a mathematically rigorous sociotechnical model. This alternative model would be parametrised by the outputs of the procedural model described through this dissertation. 
\subsection{Parametrisation}
Sociotechnical models have few to no concrete definitions in place. As a result, it can be difficult to discuss the properties of sociotechnical systems, as different people refer to different things. \\
However, the emergent properties of sociotechnical systems arise from two places:
\begin{itemize}
\item The generally deterministic running of the technical aspect of a system, which can break unexpectedly, leading to chaotic results
\item The seemingly random behaviour of the social component of the system, which leads to unpredictability by definition
\end{itemize}
However, using the atomic layer structure used to create the sociotechnical systems for these experiments, one could parametrise sociotechnical systems into properties of the social and technical aspects, which in turn have their own parameters to be defined.\\
Defining all of these relevant parameters would allow for characterisation of each sociotechnical atom by its affect on the different sociotechnical parameters, rather than they system's environment. As a result, each atom becomes a function which modifies values within the dimensions of the defined parameters. 

\subsection{Functions mapping to sociotechnical space}
If each atom modifies values within some sociotechnical dimensions, we can characterise an atom by specifying how it maps between points in sociotechnical space.\\
A natural extension of this is that flows can be defined by the composition of atoms' functions, such that all activities within the atomic layer model can be described as some mapping from one set of states within the sociotechnical space to another.\\
As a result, the ideal case described by a given sociotechnical layer model can be represented mathematically as a set of functions. However, the stress testing used to identify anomalies in sociotechnical systems then becomes alterations to this set of functions. One could, in fact, specify these alterations along these same sociotechnical dimensions, as these are the only values being changed. \\
Therefore, the output of testing the atomic model becomes a function space, where every point in the space is a behaviour characterised by how its emergent properties diverge from the properties of the ideal case. Moreover, this makes behaviour change a function mapping between points in the sociotechnical function space. The mapping of the behaviour change function is equivalent to the output of that change as modelled by code fuzzing, meaning that the fuzzing tools described in this dissertation is implicitly a tool for exploring this model.

\subsection{Creating a mathematically rigorous sociotechnical model}
\label{rigorous_sociotechnical_model}
Some future work to propose could be a realisation of this mathematical representation of a sociotechnical system. Defining mathematics and terms for the model would be an important step toward creating a single model for sociotechnical systems which can be analysed, for which tools are already available, and which unifies the jargon in the field such that researchers can discuss sociotechnical systems without the risk of ambiguity. 


\chapter{conclusion}
\label{conclusion}

%\begin{appendices}
%
%\end{appendices}

%\bibliographystyle{plain}
%\bibliography{bibtex_file}

\end{document}
